### PR TITLE
Stats page

### PR DESCRIPTION
**Pull request by arthcp**
- Adds Stats pages to view data from union contracts.
- Also adds fallback mechanism to use infura in case user is not signed in to any wallet.

Linear task - https://linear.app/union/issue/UNI-69/stats-dashboard

### CODE REVIEW

**Comment by mirshko** [comment]
#### 📝Changed routes:


| [**/stats/asset-manager**](https://union-p4rcq01sr.vercel.app/stats/asset-manager) | [**/stats/gov-vars**](https://union-p4rcq01sr.vercel.app/stats/gov-vars) |
|:-:|:-:|
|<a href="https://union-p4rcq01sr.vercel.app/stats/asset-manager">Screenshot of /stats/asset-manager</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/cQ5k2jKvIRlJzeKQe3ceeKvaWKo_.png">(view full size)</a> |<a href="https://union-p4rcq01sr.vercel.app/stats/gov-vars">Screenshot of /stats/gov-vars</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/M7tLI0OetU9d82gmZwq_7yXP8D4_.png">(view full size)</a> |



| [**/stats**](https://union-p4rcq01sr.vercel.app/stats) | [**/stats/market-settings**](https://union-p4rcq01sr.vercel.app/stats/market-settings) |
|:-:|:-:|
|<a href="https://union-p4rcq01sr.vercel.app/stats">Screenshot of /stats</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/DHxNJ0CUjQFFYtedXdUToMBKGw0_.png">(view full size)</a> |<a href="https://union-p4rcq01sr.vercel.app/stats/market-settings">Screenshot of /stats/market-settings</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/wLehvP32m1AJZMkacV4xKvoGgGU_.png">(view full size)</a> |



| [**/stats/u-token**](https://union-p4rcq01sr.vercel.app/stats/u-token) | [**/stats/user-manager**](https://union-p4rcq01sr.vercel.app/stats/user-manager) |
|:-:|:-:|
|<a href="https://union-p4rcq01sr.vercel.app/stats/u-token">Screenshot of /stats/u-token</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/B8w8GWuggdiRQVxVVLFat4p2QLo_.png">(view full size)</a> |<a href="https://union-p4rcq01sr.vercel.app/stats/user-manager">Screenshot of /stats/user-manager</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/ogAvcDyQsZDinJJ3m1xkL_LTNLw_.png">(view full size)</a> |







Commit a044e82b1bdc855b23dca704d453628b956f6ecf (https://union-p4rcq01sr.vercel.app).

**Comment by maxweng** [comment]
@arthcp Pages looking good. And I get some errors for Infura requests in the web console. Can you look into that? 

image

**Comment by arthcp** [comment]
@maxweng If running locally, you need to set NEXT_PUBLIC_INFURA_KEY environment variable as infura key. The error is probably because of that.

**Comment by kingjacob** [comment]
1. Seems to be a discrepancy with UNION supply displayed in /stats(100M) & /governance (99,999,999)
2. There's a $0.50 discrepancy between what's available as credit and what is the sum of udai&reserves)
3. Not sure what 120 in dai in contract relates to
2. Stats shouldn't be linked in the main nav only the footer nav and view detailed stats
3. Is the timelock set at 49 DAYs or is that a ui error?
4. H1 "Union stats" -> H2 
5. Total Redeemable should be denominated in DAI, no?
6. Make sure not to revert the allowances to be required each time 
5. Exchange rate is either wrong in the contract or being rounded up(screenshot)
Screen Shot 2021-02-12 at 2 17 12 PM

**Comment by arthcp** [comment]
From the points mentioned by @kingjacob

1 - A round figure is shown on stats page, hence the minor difference.
2 and 3 - being discussed at https://linear.app/union/issue/UNI-81
4 - done
5 - Timelock is set as 604800 blocks in contract. With a blockspeed of 4sec this equals 28 days. But recently blockspeed was changed to 7sec in our project config so the calculation equals 49 days. I can change back the config if it was not intended.
6 - done
7 - done
8 - Need more clarity
9 - In contract the exchange rate is 1.00027267518, on UI it is being shown as 1.00 due rounding.

**Review by twygod — APPROVED** [review]

**Review by twygod — APPROVED** [review]

**Review by twygod — APPROVED** [review]

**Review by twygod — CHANGES_REQUESTED** [review]
The return value of the delay method of the timelock contract is in seconds, not the number of blocks

**Comment by arthcp** [comment]
Did the changes requested by @twygod and increased precision while formatting stats

**Comment by maxweng** [comment]
@arthcp hey I see you using typescript for the hooks, while others using javascript. Is there a reason you mixing those two?

**Comment by arthcp** [comment]
@maxweng I think the hooks were already a mixture of js and ts. And I used ts as much as I can since having type checks is helpful.

**Review by twygod — APPROVED** [review]

**Pull request merged**
